create table target
(
    id   int generated by default as identity primary key,
    name varchar(100)
);

create table person
(
    id           int generated by default as identity primary key,
    name         varchar(200) not null,
    email        varchar(100) unique,
    age          int check (age >= 0 and age < 150),
    weight       int check (weight >= 0 and weight <= 300),
    height          int check (height >= 0 and height <= 300),
    target_id       int references target (id),
    calorie_norm    int
);

create table dish
(
    id              int generated by default as identity primary key,
    name            varchar(200) not null unique,
    calories        int check (calories >= 0),
    proteins        numeric(5, 2) check (proteins >= 0),
    fats            numeric(5, 2) check (fats >= 0),
    carbohydrates   numeric(5, 2) check (carbohydrates >= 0)
);

create table food_intake
(
    id              int generated by default as identity primary key,
    person_id       int references person (id),
    name            varchar(100),
    create_date     timestamp not null
);

create table food_intake_dish
(
    id                    int generated by default as identity primary key,
    food_intake_id        int references food_intake(id),
    dish_id               int references dish(id)
);

insert into target (name)
values ('Похудение');
insert into target (name)
values ('Поддержание');
insert into target (name)
values ('Набор массы');